/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.fastybunny.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Ventana principal del sistema Fasty Bunny.
 * Contiene un JDesktopPane para alojar las ventanas internas (JInternalFrame)
 * y una barra de menú para navegar entre las diferentes funcionalidades.
 * @author PC-04
 */
public class FrmMenu extends javax.swing.JFrame {

    // Instancias de los formularios internos para aplicar el patrón Singleton (una sola instancia)
    private FrmUsuarios frmUsuarios;
    private FrmRoles frmRoles;
    private FrmProductos frmProductos;
    private FrmCategorias frmCategorias;

    /**
     * Constructor del FrmMenu.
     * Inicializa los componentes, establece el título y maximiza la ventana.
     */
    public FrmMenu() {
        initComponents();
        // Establece el título de la ventana principal.
        this.setTitle("Fasty Bunny - Menú Principal");
        // Maximiza la ventana para que ocupe toda la pantalla.
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuItemRoles = new javax.swing.JMenuItem();
        mnuItemUsuarios = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mnuItemRegistrarProductos = new javax.swing.JMenuItem();
        mnuItemCategorias = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuariosC.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");

        mnuItemRoles.setText("Roles de Usuario");
        mnuItemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRolesActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemRoles);

        mnuItemUsuarios.setText("Operaciones Usuarios");
        mnuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemUsuarios);

        menuBar.add(mnuUsuarios);

        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteC.png"))); // NOI18N
        mnuProductos.setText("Productos");

        mnuItemRegistrarProductos.setText("Registrar Productos");
        mnuItemRegistrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistrarProductosActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuItemRegistrarProductos);

        mnuItemCategorias.setText("Categorias de Producto");
        mnuItemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCategoriasActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuItemCategorias);

        menuBar.add(mnuProductos);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporteC.png"))); // NOI18N
        mnuReportes.setText("Reportes");
        menuBar.add(mnuReportes);

        mnuAyuda.setText("Ayuda");
        menuBar.add(mnuAyuda);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salirC.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre el formulario de gestión de usuarios (FrmUsuarios).
     * Si el formulario no está abierto, crea una nueva instancia y la muestra.
     * Si ya está abierto, lo trae al frente.
     * @param evt Evento de acción del menú.
     */
    private void mnuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUsuariosActionPerformed
        if (frmUsuarios == null || frmUsuarios.isClosed()) {
            frmUsuarios = new FrmUsuarios();
            desktopPane.add(frmUsuarios);
            frmUsuarios.setVisible(true);
        } else {
            frmUsuarios.toFront();
        }
    }//GEN-LAST:event_mnuItemUsuariosActionPerformed

    /**
     * Abre el formulario de gestión de productos (FrmProductos).
     * Si el formulario no está abierto, crea una nueva instancia y la muestra.
     * Si ya está abierto, lo trae al frente.
     * @param evt Evento de acción del menú.
     */
    private void mnuItemRegistrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistrarProductosActionPerformed
        if (frmProductos == null || frmProductos.isClosed()) {
            frmProductos = new FrmProductos();
            desktopPane.add(frmProductos);
            frmProductos.setVisible(true);
        } else {
            frmProductos.toFront();
        }
    }//GEN-LAST:event_mnuItemRegistrarProductosActionPerformed

    /**
     * Abre el formulario de gestión de categorías (FrmCategorias).
     * Si el formulario no está abierto, crea una nueva instancia y la muestra.
     * Si ya está abierto, lo trae al frente.
     * @param evt Evento de acción del menú.
     */
    private void mnuItemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCategoriasActionPerformed
        if (frmCategorias == null || frmCategorias.isClosed()) {
            frmCategorias = new FrmCategorias();
            desktopPane.add(frmCategorias);
            frmCategorias.setVisible(true);
        } else {
            frmCategorias.toFront();
        }
    }//GEN-LAST:event_mnuItemCategoriasActionPerformed

    /**
     * Abre el formulario de gestión de roles (FrmRoles).
     * Si el formulario no está abierto, crea una nueva instancia y la muestra.
     * Si ya está abierto, lo trae al frente.
     * @param evt Evento de acción del menú.
     */
    private void mnuItemRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRolesActionPerformed
        if (frmRoles == null || frmRoles.isClosed()) {
            frmRoles = new FrmRoles();
            desktopPane.add(frmRoles);
            frmRoles.setVisible(true);
        } else {
            frmRoles.toFront();
        }
    }//GEN-LAST:event_mnuItemRolesActionPerformed

    /**
     * Maneja el evento de clic en el menú "Salir".
     * Muestra un diálogo de confirmación y cierra la aplicación si el usuario acepta.
     * @param evt Evento de clic del ratón.
     */
    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que quieres salir?",
                "Confirmar Salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuItemCategorias;
    private javax.swing.JMenuItem mnuItemRegistrarProductos;
    private javax.swing.JMenuItem mnuItemRoles;
    private javax.swing.JMenuItem mnuItemUsuarios;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
